name: Build and test solution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal /p:CollectCoverage=true --collect:"XPlat Code Coverage"

    - name: Create NuGet Packages
      run: dotnet pack -c Release

    - name: Publish NuGet Packages
      run: nuget push **/*.nupkg -ApiKey ${{ secrets.DOTLAND_PACKAGES_KEY }} -Source https://api.nuget.org/v3/index.json -NoSymbols true -SkipDuplicate
